### ISSUE TITLE
Online Demo please?

### ISSUE THREAD

**Issue by winkler1** [gcedo/react-solitaire#1]
Hi-
 This is great! Very up to date, uses functional components and latest practices. Would it be possible to get a gh-pages demo up? Would love to add to react.rocks.
Thanks,
Jeff

**Comment by gcedo** [comment]
Hi Jeff! 
Absolutely, a demo is absolutely a must, I should have some time today...I am in the middle of a job/home/country change :smile: 

Thank you for your interest!

Cheers,
Edo

**Comment by winkler1** [comment]
Wow - big changes :+1: Look forward to seeing it, thanks! Amazingly, no one has done a Solitaire game yet either :)

**Comment by gcedo** [comment]
Hi Jeff! The demo is [published online](http://gcedo.github.io/react-solitaire/dist/index.html).
