### ISSUE TITLE
Missing card

### ISSUE THREAD

**Issue by stanlemon** [gcedo/react-solitaire#3]
I'm honestly not sure how I made this happen, but the King of Spades appears to be missing. There are no cards left for me to shuffle through.

<img width="993" alt="screenshot 2015-10-31 21 15 45" src="https://cloud.githubusercontent.com/assets/86314/10866729/c4061414-8014-11e5-984a-58757c8503fa.png">

**Comment by gcedo** [comment]
Thanks for the report, I'll have a look! Also the symbol thingy is quite annoying... :disappointed:

**Comment by gcedo** [comment]
I have added a test to check that all the cards are dealt at the beginning of the match...I think that the King of Spades was somehow "swallowed" during the match. 

I will leave the issue open, hoping to get a clue of what could have gone wrong :confused:

**Comment by stanlemon** [comment]
Ok, sorry for the lack of detail - if I see it happen again I will let you know.  Bug aside, really awesome project and a great showcase for what's possible with React and Redux!  Thanks for building this!

**Comment by gcedo** [comment]
Thanks, really appreciate :smile: 

Well sometimes bugs just happen and you were not ready to think about how to reproduce it :wink:

Thanks instead for noticing and reporting a quite non negligible issue :smile: 

![You're awesome](http://images6.fanpop.com/image/polls/1379000/1379803_1401207046483_full.jpg)
